research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task_1:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst_1
  context:
    - research_task
  human_input: True

reporting_task_2:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst_2
  context:
    - research_task
  human_input: True

aggregation_task:
  description: >
    Consolidate the results of the two reports received, and create a JSON object with the following structure:
    
      "report_good": "<content of report 1>",
      "report_bad": "<content of report 2>"

    Ensure that the final JSON is valid, well-structured, and ready to be consumed by other agents or systems.
  expected_output: >
    A valid and well-structured JSON object with the fields "report_1" and "report_2", containing the respective contents received.
  agent: aggregator
  context:
    - reporting_task_1
    - reporting_task_2
  agent: aggregator